baseURL = 'http://kinipk.moe/'
languageCode = 'en-us'
title = 'Kinipk Site'

[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "List"
        pre = "list"
        url = "/posts/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3
        
